# version: '3.8'

services:
  client:
    build:
      context: ./client # Path to the client folder
    ports:
      - "3000:3000" # Expose port 3000 for the client
    depends_on:
      - server # Make sure the server is up before the client starts

  server:
    build:
      context: ./server # Path to the server folder
    ports:
      - "5000:5000" # Expose port 5000 for the server
    env_file:
      - ./server/config.env # Use the .env file for server env variables
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
